### ISSUE TITLE
Under common circumstances, annotations get assigned to taxon:0 in GAFs during noctua merge

### ISSUE THREAD

**Issue by kltm** [geneontology/pipeline#239]
When looking at the pipeline results for ZFIN, namely the "final" GAF, almost 7k annotations have been assigned to `taxon:0`. 

There are a few theories about why this may be occurring and we are working to duplicate it locally--so far it has only been found in the pipeline "Mega-step".

While we ran into this most seriously with ZFIN so far, we have also noted it occurring with Xenbase (~30 annotations) and WB (~1 annotation).

Tagging @sierra-moxon @dustine32 

Looping in @vanaukenk (I'm not sure what project to this under) @ukemi

**Comment by kltm** [comment]
Currently, all files seem to be correct up until the point where the upstream GAF, the upstream GPI, and the internally produced GPAD are all merged into a single file. We are currently working on isolating the exact step/command where the bad merging takes place and simulating it.

**Comment by kltm** [comment]
A current theory is that it may have to do with either the GPI not being found at this step correctly of not being read correctly--this may explain why there is a variation in how bad this problem seems to be in various resources.

**Comment by vanaukenk** [comment]
@kltm 

Do you have access to the ~1 WB annotation that's getting assigned taxon:0? If I can the annotation, this might help troubleshoot.

For WB specifically, I'm wondering about possible changes to WBGene metadata in the gpi file.

Wrt projects, we could put this ticket in the Xenbase and WB imports projects; I didn't make a ZFIN project, but perhaps @sierra-moxon could create one if this would be useful?

**Comment by dustine32** [comment]
Ontobio is taking the `source_gaf` (e.g. `gene_association2.2_automated_only.zfin.gz` specified in [zfin.yaml](https://github.com/geneontology/go-site/blob/a7397f92cc2fce7cddf921c1b8c559a074baac85/metadata/datasets/zfin.yaml#L19)), making a GPI from it, and then using _only_ this GAF-derived GPI when converting `noctua_zfin.gpad` to GAF. Since the annotated entities in this GAF do not cover the full ZFIN "super-set" of all entities, many of the entities coming from the `noctua_zfin.gpad` will not have full gene info (such as `taxon`) in the merged final GAF. (BTW, a reminder that there is no `taxon` column in GPAD)

To fix this, we're going to look in the group datasets YAML and try grabbing the correct `gpi` for the source `dataset`. For example:
```
datasets:
 -
   id: zfin.gaf
   label: "zfin gaf file"
   description: "gaf file for zfin from Zebrafish Information Network"
   url: http://current.geneontology.org/annotations/zfin.gaf.gz
   type: gaf
   dataset: zfin
   submitter: zfin
   compression: gzip
   source: http://zfin.org/downloads/gene_association2.2_automated_only.zfin.gz
   entity_type:
   status: active
   species_code: Drer
   taxa:
    - NCBITaxon:7955
 -
   id: zfin.gpi
   label: "zfin gpi file"
   description: "gpi file for zfin from Zebrafish Information Network"
   url: http://current.geneontology.org/annotations/zfin.gpi.gz
   type: gpi
   dataset: zfin
   submitter: zfin
   compression: gzip
   source: https://zfin.org/downloads/zfin.gpi.gz
   entity_type:
   status: active
   species_code: Drer
   taxa:
    - NCBITaxon:7955
```
When operating on `source_gaf` of `zfin.gaf`, we'll look at its `dataset`, then match to another `dataset` where `type` equals `gpi`. If a GPI is found, we'll then merge it into the GAF-derived GPI data to be used in creating the final `zfin.gaf` product (which includes the merged Noctua and PAINT annotations).

@kltm @sierra-moxon @vanaukenk I've managed to code this change to fix our current ZFIN `taxon:0` issue. Let me know if you have thoughts/changes to how this should work. Thanks!
